### ISSUE TITLE
[ANNOUNCEMENT FROM SUCS TEAM - PLEASE VIEW]

### ISSUE THREAD

**Issue by Nambaseking01** [Nambaseking01/Scratch-Ultimate-Coding-Shop#10]
[ANNOUNCEMENT]

We have replaced the SUCS banner from the `index.html` with a header text since the image was way too small to fit in the website. We have tried our best to make it fit in, as you can see on pull requests #7 and #9, but unfortunately the image had to get bigger in width and height and it was large enough to almost cover up the entire website. 

It would be nice if someone could make a bigger version of the banner and post it here! We will keep this issue open until someone gives a banner good enough to fit inside the website. We are sharing this issue in all of our internet branches. You should also share this with the world!

Further notes:
> [UPDATE]
> 
> Until this minor problem gets solved, we are labelling every banner related thing to a new label named "banner testing". When it is solved, we will delete the label.

> [UPDATE]
> 
> If you are going to submit a banner, please provide a hex code for the background colour so that it matches with the banner. If you do not, we will have to keep this issue open until someone else provides a nice hex code.

Thank you for reading,
-The SUCS Team-

**Comment by smileycreations15** [comment]
@Nambaseking01 Ok! Sure! I can ;)

**Comment by Nambaseking01** [comment]
@smileycreations15 Please try!

**Comment by Nambaseking01** [comment]
[UPDATE]

Until this minor problem gets solved, we are labelling every banner related thing to a new label named "banner-testing". When it is solved, we will delete the label.

**Comment by Nambaseking01** [comment]
Moving this to the top of the issues section for extra attention.

**Comment by Nambaseking01** [comment]
[UPDATE]

If you are going to submit a banner, please provide a hex code for the background colour so that it matches with the banner. If you do not, we will have to keep this issue open until someone else provides a nice hex code.

**Comment by smileycreations15** [comment]
Ok! I will make a CSS banner.

**Comment by Nambaseking01** [comment]
@smileycreations15 Thank you!

**Comment by Nambaseking01** [comment]
> Ok! I will make a CSS banner.

Please be quick, we could need this banner for v0.0.3!
