### ISSUE TITLE
[Bug] Clock functions seem to be mishandling load.js!

### ISSUE THREAD

**Issue by Nambaseking01** [Nambaseking01/Scratch-Ultimate-Coding-Shop#15]
**Describe the bug**
The clock function in the `clock.js` file is stopping the loading function inside the `load.js` one to work. The loader just keeps rotating and rotating, and now I had to change the entire code to a comment since it was impossible to keep that.

**Expected behavior**
The loading GUI needs to work properly when all functions get fired.

**Additional context**
None for now.

**Comment by smileycreations15** [comment]
@Nambaseking01 It was a misplaced semicolon.

**Comment by Nambaseking01** [comment]
Oh! But I cannot seem to see the clock working below the text in the website!

**Comment by Nambaseking01** [comment]
@smileycreations15  Thank you for fixing the bug!

**Comment by smileycreations15** [comment]
@smileycreations15 no problem :)

**Comment by Nambaseking01** [comment]
@smileycreations15 Please see the new issue at `smileycreations15.github.io`!

**Comment by smileycreations15** [comment]
Ok1

**Comment by smileycreations15** [comment]
@Nambaseking01 Also the code that messed up load.js is a forgotten quote.
