### ISSUE TITLE
[Question] Where is the main page?

### ISSUE THREAD

**Issue by jbrow78** [Nambaseking01/Scratch-Ultimate-Coding-Shop#3]
**A concise version of what your question is**
Where is the main format at?
**Your question in detail**
Where is the URL to the website at?
**Additional notes**

**Comment by Nambaseking01** [comment]
The website is at: https://nambaseking01.github.io/Scratch-Ultimate-Coding-Shop/

Thank you for visiting!
-The SUCS Team-
