### ISSUE TITLE
[Idea] Center Page and BG gradient

### ISSUE THREAD

**Issue by jbrow78** [Nambaseking01/Scratch-Ultimate-Coding-Shop#5]
**Is your feature request related to a problem? Please describe.**
N/A
**Describe the solution you'd like**
Center and add an orange gradient to the BKG
**Describe alternatives you've considered**
Not really, this is simple
**Additional context**

**Comment by Nambaseking01** [comment]
Hello! I cannot seem to understand what you mean with this. Could you please elaborate?

Thanks!
-The SUCS Team-

**Comment by Nambaseking01** [comment]
Please accept this invitation: https://github.com/Nambaseking01/Scratch-Ultimate-Coding-Shop/invitations

If you do not accept, you cannot be an assignee for the bug report template!

**Comment by Nambaseking01** [comment]
I now seem to understand this enhancement. Unfortunately, this does not match with the procedures we are currently taken but this move has to be taken in the near future. Anyone who wants to continue the discussion, please go to issue #10 and see the second further note to start posting.

Thank you,
-The SUCS Team-
